---
- hosts: all
  remote_user: root
  become: yes
  become_user: root
  gather_facts: false
  pre_tasks:
    - raw: apt-get update
    - raw: sudo apt-get -y install python
    - name: Turning on facts gathering...
      action: setup

  #vault managed
  vars_files:

  roles:
    - { role: golang, package_version: '1.8.1' } 
    - { role: geoip_group_server_settings, sealoff_iptables: true, swapfile_enabled: true, swapfile_size: 1GiB }
    - { role: freegeoip, package_version: '3.2' }

