---
ufsrv_src_enabled: yes
package_name: ufsrvapi
ufsrv_configfile_name: ufsrv.lua
default_pid_directory: /var/run/ufsrv
ufsrv_server_type: ufsrv
tmp_download_dir: /home/devops
src_location_prefix: /home/devops
base_install_dir: /opt
package_git_url: https://github.com/unfacd/ufsrv.git
package_version: ""
ufsrv_stats_address: "{{ hostvars[inventory_hostname].private_ip }}"
ufsrv_stats_port: 8125
ufsrv_commandline_params:
    - '-i {{ ufsrv_instance_id }}'
    - '-c {{ base_install_dir }}/ufsrv/etc'
    - '-f {{ ufsrv_configfile_name }}'
    - '-s {{ ufsrv_server_type }}'
    - '-d 1'
ufsrv_config:
  ufsrv_workers_thread_pool: 2
  session_workers_thread_pool: 2
mariadb_mysql_users:
     - name: ufsrv
       hosts:
#         - '%'
         - "10.1.0.0/255.255.0.0"
         - "10.1.16.1"
         - "10.1.16.2"
       password: "{{ ufsrv_db_ufsrv_password }}"
       encrypted: no
       priv: 'ufsrv.*:ALL'
       state: present
       append_privs: no
