freegeoip_enabled: yes
tmp_download_dir: '/tmp'
base_install_dir: '/opt'
package_version: '3.2'
package_name: 'freegeoip'
package_download_url: 'https://github.com/fiorix/freegeoip/releases/download/v{{ package_version }}/freegeoip-{{ package_version }}-linux-amd64.tar.gz'
protoc_install_dir: /opt
freegeoip_params:
    - '-http={{ hostvars[inventory_hostname].private_ip }}:{{ ufsrv_geoip_node_port| default(19800, true)}}' 
    - '-use-x-forwarded-for'
